[package]
name = "taskharbor-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
taskharbor-adapters = { path = "../../crates/adapters" }
tokio.workspace = true

[dev-dependencies]
image.workspace = true
sqlx.workspace = true
taskharbor-core = { path = "../../crates/core" }
tempfile = "=3.27.0"
time.workspace = true

[lints]
workspace = true
